name: gamelog
description: "Gamelog android application for Application Development."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.3+1
  dartz: ^0.10.1

  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  curved_labeled_navigation_bar: ^2.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^1.1.1
  custom_date_range_picker: ^1.2.0
  grpc: ^4.0.0
  protobuf: ^5.0.0
  image_picker: ^1.0.7
  video_player: ^2.8.1
  path_provider: ^2.1.2
  video_thumbnail: ^0.5.3
  socket_io_client: ^2.0.3+1
  awesome_notifications: ^0.10.1
  collection: ^1.18.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env